<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1

|Term|Brief description|
|:-|:-|
|Subsetting|*Subsetting means to ‘select’*|
|Indexing|It is to choose 1 element of a list|
|Slicing|It is to choose some range of the elements|
|Masking|*The answer to my question (np_array > 5) is in the form of a ‘Yes’/‘No’ or True/False format. I can use this True/False format to ask NumPy to show me only those that are True*|

## Exercise 2

In [24]:
import numpy as np

np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

my_mask = np_array_2d[:,0]       #get array of the 0th index of all elements 

my_mask = my_mask.astype(int)    #convert all elements into int

my_mask = my_mask % 2            #find it they are even or odd

my_mask = my_mask > 0            #if is 0, it is even. if it is 1, it is odd

new_array = np_array_2d[my_mask]

print(new_array[:, 1])



['A' 'C' 'E' 'G' 'I']


## Exercise 3

In [96]:
import numpy as np


np_array = np.array([[66, 50, 57, -1, -1],
            [92, -1, 88, -1, -1],
            [75, -1, -1, 76, -1],
            [-1, 51, 87, -1, -1],
            [71, -1, 67, -1, 69]])


my_mask1 = np_array > 50 
my_mask2 = np_array < 50
my_mask3 = ( np_array == 50 )

np_array[my_mask1] = 1
np_array[my_mask2] = -1
np_array[my_mask3] = 0


print(np_array)    

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]
