<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [3]:
import numpy as np
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

In [7]:
# Pick one
x = py_list  # OR
#x = np_array

In [50]:
x[1::-1]  # start at 1 and go backwards

['b2', 'a1']

## 1.2 Arrays only | Subsetting by masking

In [19]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = (np_array > 3) & (np_array < 8)
# for numpy use & not 'and'

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [23]:
np_array[3:7]

array([4, 5, 6, 7])

In [21]:
np_array[my_mask]    #more intelligent of the above

array([4, 5, 6, 7])

In [24]:
my_mask.sum()

np.int64(4)

In [32]:
my_mask = ~((np_array > 3) & (np_array < 8))               # '~' means 'NOT'
np_array[my_mask]

array([ 1,  2,  3,  8,  9, 10])

In [29]:
np_array[~((np_array > 3) & (np_array < 8))]                 # '~' means 'NOT'

array([ 1,  2,  3,  8,  9, 10])

In [ ]:
np_array

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

In [33]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [40]:
py_list_2d[3]

[4, 'D']

In [39]:
np_array_2d[3]

array(['4', 'D'], dtype='<U21')

In [42]:
py_list_2d[3][1]

'D'

In [41]:
np_array_2d[3,1]   #use coordinates system

np.str_('D')

In [43]:
np_array_2d[3][1]

np.str_('D')

In [45]:
list_3d = [[[1,1],[2,2]],[[3,3],[4,4]],[[5,5],[6,6]]] #3d list
list_3d[1][1][1]

4

## 1.4 Growing lists

In [1]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [2]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x


[1, 2, 3, 4]

In [3]:
x=[1]
x+= [2]
x+= [3]
x+= [4]
x


[1, 2, 3, 4]

In [4]:
x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

In [8]:
x = [1,2,3]
x.extend([1,2,3])
x

[1, 2, 3, 1, 2, 3]

In [12]:
x = [1,2,3]
x.append([4,5,6])
x


[1, 2, 3, [4, 5, 6]]

In [14]:
x = [1,2,3]
x.insert(1,'0')
x

[1, '0', 2, 3]

# Some loose ends

## 1.5 Tuples

In [23]:
a = [1,2,3]
a[0] = 1234
a

[1234, 2, 3]

In [ ]:
a = (1,2,3)

## 1.6 Be VERY careful when copying

In [25]:
x=[1, 2, 3]
y=x           # DON'T do this!    use y = x.copy()    instead
z=x           # DON'T do this!

# now x,y,z looks at the same list so when the list changes, all changes

In [28]:
y[0] =1234

In [29]:
print(f'{x=},{y=},{z=}')

x=[1234, 2, 3],y=[1234, 2, 3],z=[1234, 2, 3]


## Footnotes